import { formatDateTime, formatTime } from "@/lib/utils/dates";
import type { Attachment } from "@/types";

import {
  REPORT_EMPTY_MESSAGES,
  REPORT_IMPORTANCE_LABELS,
  dailyUpdateBodyCell,
  dailyUpdateTitleCell,
  recordDocuments,
  recordPhotos,
  neutralizeFormula,
  noDailyUpdatesMessage,
  reportRangeHeading,
} from "./labels";
import type { ReportData } from "./types";

/**
 * CSV export (RFC 4180): UTF-8 with BOM (so Excel detects the encoding), CRLF line endings, quoted
 * fields where needed and a formula-injection guard on every text cell.
 */

type CsvCell = string | number;

const BOM = "﻿";
const CRLF = "\r\n";

const DAILY_HEADERS = [
  "Office",
  "Date",
  "Update Title",
  "Update Description",
  "Milestone Title",
  "Milestone Description",
  "Milestone Remarks",
  "Photos",
  "Documents",
];

const VISITOR_HEADERS = [
  "Office",
  "Date",
  "Name",
  "Purpose",
  "Arrival",
  "Departure",
  "Importance",
  "Remarks",
  "Photos",
  "Documents",
];

const ATTACHMENT_HEADERS = [
  "Office",
  "Date",
  "Attached To",
  "Title",
  "Type",
  "File Name",
  "File URL",
];

const COLUMN_COUNT = Math.max(
  DAILY_HEADERS.length,
  VISITOR_HEADERS.length,
  ATTACHMENT_HEADERS.length,
);

function escapeCell(value: CsvCell): string {
  if (typeof value === "number") return String(value);
  const text = neutralizeFormula(value);
  return /[",\r\n]/.test(text) || text !== text.trim() ? `"${text.replace(/"/g, '""')}"` : text;
}

/** Every row has the same number of fields (RFC 4180 §2.4). */
function toLine(cells: CsvCell[]): string {
  const padded = cells.length < COLUMN_COUNT ? [...cells, ...Array<string>(COLUMN_COUNT - cells.length).fill("")] : cells;
  return padded.map(escapeCell).join(",");
}

/** Attachment cell: count plus file URLs, e.g. "2 files: https://…; https://…". */
function attachmentCell(files: Attachment[]): string {
  if (files.length === 0) return "0";
  const label = files.length === 1 ? "1 file" : `${files.length} files`;
  return `${label}: ${files.map((file) => file.fileUrl).join("; ")}`;
}

export function reportToCsv(data: ReportData): string {
  const { meta, sections } = data;
  const rows: CsvCell[][] = [
    [meta.systemName],
    ["Office", meta.officeLabel],
    ["Report Type", meta.typeLabel],
    [reportRangeHeading(meta.from, meta.to), meta.rangeLabel],
    ["Generated At", formatDateTime(meta.generatedAt)],
    ["Generated By", meta.generatedBy],
    [],
    ["Daily Updates & Milestones"],
    DAILY_HEADERS,
  ];

  let dailyRows = 0;
  for (const section of sections) {
    for (const record of section.dailyRecords) {
      const base = [
        section.office.name,
        record.date,
        dailyUpdateTitleCell(record.dailyUpdates),
        dailyUpdateBodyCell(record.dailyUpdates),
      ];
      const attachments = [attachmentCell(recordPhotos(record)), attachmentCell(recordDocuments(record))];
      if (record.milestones.length === 0) {
        rows.push([...base, "", "", "", ...attachments]);
      } else {
        for (const milestone of record.milestones) {
          rows.push([...base, milestone.title, milestone.description, milestone.remarks, ...attachments]);
        }
      }
      dailyRows += 1;
    }
  }
  if (dailyRows === 0) rows.push([noDailyUpdatesMessage(meta.from, meta.to)]);

  rows.push([], ["Visitors"], VISITOR_HEADERS);

  let visitorRows = 0;
  for (const section of sections) {
    for (const visitor of section.visitors) {
      rows.push([
        section.office.name,
        visitor.date,
        visitor.name,
        visitor.purpose,
        formatTime(visitor.timeArrived),
        visitor.timeDeparted ? formatTime(visitor.timeDeparted) : "",
        REPORT_IMPORTANCE_LABELS[visitor.importance],
        visitor.remarks,
        attachmentCell(visitor.photos),
        attachmentCell(visitor.documents),
      ]);
      visitorRows += 1;
    }
  }
  if (visitorRows === 0) rows.push([REPORT_EMPTY_MESSAGES.visitors]);

  // One row per file, naming what it was attached to (the day, an update, a milestone or a visitor).
  rows.push([], ["Attachments"], ATTACHMENT_HEADERS);

  let attachmentRows = 0;
  const addFiles = (office: string, date: string, source: string, title: string, files: Attachment[], kind: string) => {
    for (const file of files) {
      rows.push([office, date, source, title, kind, file.fileName, file.fileUrl]);
      attachmentRows += 1;
    }
  };
  for (const section of sections) {
    const office = section.office.name;
    for (const record of section.dailyRecords) {
      record.dailyUpdates.forEach((update, index) => {
        const title = `${index + 1}. ${update.title}`;
        addFiles(office, record.date, "Daily Update", title, update.photos, "Photo");
        addFiles(office, record.date, "Daily Update", title, update.documents, "Document");
      });
      record.milestones.forEach((milestone, index) => {
        const title = `${index + 1}. ${milestone.title}`;
        addFiles(office, record.date, "Milestone", title, milestone.photos, "Photo");
        addFiles(office, record.date, "Milestone", title, milestone.documents, "Document");
      });
      const dayTitle = dailyUpdateTitleCell(record.dailyUpdates);
      addFiles(office, record.date, "Daily Record", dayTitle, record.photos, "Photo");
      addFiles(office, record.date, "Daily Record", dayTitle, record.documents, "Document");
    }
    for (const visitor of section.visitors) {
      addFiles(office, visitor.date, "Visitor", visitor.name, visitor.photos, "Photo");
      addFiles(office, visitor.date, "Visitor", visitor.name, visitor.documents, "Document");
    }
  }
  if (attachmentRows === 0) rows.push(["No attachments."]);

  return BOM + rows.map(toLine).join(CRLF) + CRLF;
}
