import ExcelJS from "exceljs";

import { businessDateToUtc, formatDateTime, formatTime } from "@/lib/utils/dates";
import type { Attachment } from "@/types";

import {
  REPORT_EMPTY_MESSAGES,
  REPORT_IMPORTANCE_LABELS,
  dailyUpdateBodyCell,
  dailyUpdateTitleCell,
  recordDocuments,
  recordPhotos,
  isLinkableUrl,
  neutralizeFormula,
  noDailyUpdatesMessage,
  reportRangeHeading,
} from "./labels";
import type { ReportData, ReportTotals } from "./types";

/**
 * Excel export: "Summary", "Daily Updates", "Milestones", "Visitors" and "Attachments" (clickable links).
 * Text cells pass through the formula-injection guard; business dates are real Excel dates.
 */

type CellValue = string | number | Date | ExcelJS.CellHyperlinkValue | null;

interface ColumnSpec {
  header: string;
  width: number;
  date?: boolean;
}

const DATE_FORMAT = "dd mmm yyyy";
const HEADER_FILL: ExcelJS.Fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE2E8F0" } };
const HEADER_BORDER: Partial<ExcelJS.Borders> = { bottom: { style: "thin", color: { argb: "FF94A3B8" } } };
const LINK_FONT: Partial<ExcelJS.Font> = { color: { argb: "FF1D4ED8" }, underline: true };
const MUTED_FONT: Partial<ExcelJS.Font> = { italic: true, color: { argb: "FF64748B" } };

function text(value: string): string {
  return neutralizeFormula(value);
}

function fileNames(files: Attachment[]): string {
  return files.map((file) => text(file.fileName)).join("\n");
}

function styleHeaderRow(row: ExcelJS.Row): void {
  row.font = { bold: true };
  row.alignment = { vertical: "middle", wrapText: true };
  row.eachCell((cell) => {
    cell.fill = HEADER_FILL;
    cell.border = HEADER_BORDER;
  });
}

/** Adds a data sheet with a bold, frozen, filterable header row. */
function addTableSheet(workbook: ExcelJS.Workbook, name: string, columns: ColumnSpec[]): ExcelJS.Worksheet {
  const sheet = workbook.addWorksheet(name, { views: [{ state: "frozen", ySplit: 1 }] });
  sheet.columns = columns.map((column) => ({
    header: column.header,
    width: column.width,
    style: column.date ? { numFmt: DATE_FORMAT } : undefined,
  }));
  styleHeaderRow(sheet.getRow(1));
  sheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: columns.length } };
  return sheet;
}

function addDataRow(sheet: ExcelJS.Worksheet, values: CellValue[]): ExcelJS.Row {
  const row = sheet.addRow(values);
  row.alignment = { vertical: "top", wrapText: true };
  return row;
}

function addEmptyRow(sheet: ExcelJS.Worksheet, message: string): void {
  const row = sheet.addRow([message]);
  row.font = MUTED_FONT;
}

function totalsCells(totals: ReportTotals): number[] {
  return [totals.dailyRecords, totals.milestones, totals.visitors, totals.photos, totals.documents];
}

function buildSummarySheet(workbook: ExcelJS.Workbook, data: ReportData): void {
  const { meta, sections } = data;
  const sheet = workbook.addWorksheet("Summary");
  sheet.columns = [{ width: 34 }, { width: 16 }, { width: 15 }, { width: 13 }, { width: 11 }, { width: 11 }, { width: 12 }];

  const title = sheet.addRow([meta.systemName]);
  title.font = { bold: true, size: 14 };
  sheet.addRow([]);

  const details: [string, string][] = [
    ["Office", meta.officeLabel],
    ["Report Type", meta.typeLabel],
    [reportRangeHeading(meta.from, meta.to), meta.rangeLabel],
    ["Generated At", formatDateTime(meta.generatedAt)],
    ["Generated By", meta.generatedBy],
  ];
  for (const [label, value] of details) {
    const row = sheet.addRow([label, text(value)]);
    row.getCell(1).font = { bold: true };
  }
  sheet.addRow([]);

  const header = sheet.addRow(["Office", "Code", "Daily Updates", "Milestones", "Visitors", "Photos", "Documents"]);
  styleHeaderRow(header);

  for (const section of sections) {
    sheet.addRow([text(section.office.name), text(section.office.code), ...totalsCells(section.totals)]);
  }
  if (sections.length !== 1) {
    const total = sheet.addRow(["Total", "", ...totalsCells(data.totals)]);
    total.font = { bold: true };
    total.eachCell((cell) => {
      cell.border = { top: { style: "thin", color: { argb: "FF94A3B8" } } };
    });
  }
}

function buildDailySheets(workbook: ExcelJS.Workbook, data: ReportData): void {
  const daily = addTableSheet(workbook, "Daily Updates", [
    { header: "Office", width: 24 },
    { header: "Date", width: 13, date: true },
    { header: "Update Title", width: 32 },
    { header: "Update Description", width: 60 },
    { header: "Milestones", width: 11 },
    { header: "Photos", width: 30 },
    { header: "Documents", width: 30 },
  ]);
  const milestones = addTableSheet(workbook, "Milestones", [
    { header: "Office", width: 24 },
    { header: "Date", width: 13, date: true },
    { header: "Update Title", width: 30 },
    { header: "No.", width: 6 },
    { header: "Milestone Title", width: 32 },
    { header: "Milestone Description", width: 50 },
    { header: "Remarks", width: 36 },
  ]);

  let dailyCount = 0;
  let milestoneCount = 0;
  for (const section of data.sections) {
    const office = text(section.office.name);
    for (const record of section.dailyRecords) {
      const date = businessDateToUtc(record.date);
      const title = text(dailyUpdateTitleCell(record.dailyUpdates));
      addDataRow(daily, [
        office,
        date,
        title,
        text(dailyUpdateBodyCell(record.dailyUpdates)),
        record.milestones.length,
        fileNames(recordPhotos(record)),
        fileNames(recordDocuments(record)),
      ]);
      dailyCount += 1;
      record.milestones.forEach((milestone, index) => {
        addDataRow(milestones, [
          office,
          date,
          title,
          index + 1,
          text(milestone.title),
          text(milestone.description),
          text(milestone.remarks),
        ]);
        milestoneCount += 1;
      });
    }
  }
  if (dailyCount === 0) addEmptyRow(daily, noDailyUpdatesMessage(data.meta.from, data.meta.to));
  if (milestoneCount === 0) addEmptyRow(milestones, REPORT_EMPTY_MESSAGES.milestones);
}

function buildVisitorSheet(workbook: ExcelJS.Workbook, data: ReportData): void {
  const sheet = addTableSheet(workbook, "Visitors", [
    { header: "Office", width: 24 },
    { header: "Date", width: 13, date: true },
    { header: "Name", width: 24 },
    { header: "Purpose", width: 36 },
    { header: "Arrival", width: 11 },
    { header: "Departure", width: 11 },
    { header: "Importance", width: 12 },
    { header: "Remarks", width: 40 },
    { header: "Photos", width: 28 },
    { header: "Documents", width: 28 },
  ]);

  let count = 0;
  for (const section of data.sections) {
    for (const visitor of section.visitors) {
      addDataRow(sheet, [
        text(section.office.name),
        businessDateToUtc(visitor.date),
        text(visitor.name),
        text(visitor.purpose),
        formatTime(visitor.timeArrived),
        visitor.timeDeparted ? formatTime(visitor.timeDeparted) : "",
        REPORT_IMPORTANCE_LABELS[visitor.importance],
        text(visitor.remarks),
        fileNames(visitor.photos),
        fileNames(visitor.documents),
      ]);
      count += 1;
    }
  }
  if (count === 0) addEmptyRow(sheet, REPORT_EMPTY_MESSAGES.visitors);
}

function buildAttachmentSheet(workbook: ExcelJS.Workbook, data: ReportData): void {
  const sheet = addTableSheet(workbook, "Attachments", [
    { header: "Office", width: 24 },
    { header: "Date", width: 13, date: true },
    { header: "Record", width: 14 },
    { header: "Record Title", width: 32 },
    { header: "Type", width: 11 },
    { header: "File Name", width: 36 },
    { header: "File URL", width: 60 },
  ]);

  let count = 0;
  const addFiles = (office: string, date: string, record: string, title: string, type: string, files: Attachment[]) => {
    for (const file of files) {
      const row = addDataRow(sheet, [
        office,
        businessDateToUtc(date),
        record,
        text(title),
        type,
        text(file.fileName),
        text(file.fileUrl),
      ]);
      if (isLinkableUrl(file.fileUrl)) {
        const cell = row.getCell(6);
        cell.value = { text: text(file.fileName), hyperlink: file.fileUrl };
        cell.font = LINK_FONT;
      }
      count += 1;
    }
  };

  for (const section of data.sections) {
    const office = text(section.office.name);
    for (const record of section.dailyRecords) {
      // Files are listed against whatever they were attached to: the day, an update or a milestone.
      const fileTitle = dailyUpdateTitleCell(record.dailyUpdates);
      addFiles(office, record.date, "Daily Record", fileTitle, "Photo", record.photos);
      addFiles(office, record.date, "Daily Record", fileTitle, "Document", record.documents);
      for (const update of record.dailyUpdates) {
        addFiles(office, record.date, "Daily Update", update.title, "Photo", update.photos);
        addFiles(office, record.date, "Daily Update", update.title, "Document", update.documents);
      }
      for (const milestone of record.milestones) {
        addFiles(office, record.date, "Milestone", milestone.title, "Photo", milestone.photos);
        addFiles(office, record.date, "Milestone", milestone.title, "Document", milestone.documents);
      }
    }
    for (const visitor of section.visitors) {
      addFiles(office, visitor.date, "Visitor", visitor.name, "Photo", visitor.photos);
      addFiles(office, visitor.date, "Visitor", visitor.name, "Document", visitor.documents);
    }
  }
  if (count === 0) addEmptyRow(sheet, "No attachments.");
}

export async function reportToXlsx(data: ReportData): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = data.meta.systemName;
  workbook.title = `${data.meta.typeLabel} - ${data.meta.officeLabel} - ${data.meta.rangeLabel}`;
  workbook.created = new Date(data.meta.generatedAt);

  buildSummarySheet(workbook, data);
  buildDailySheets(workbook, data);
  buildVisitorSheet(workbook, data);
  buildAttachmentSheet(workbook, data);

  const output = await workbook.xlsx.writeBuffer();
  return Buffer.from(output as ArrayBuffer);
}
