import ExcelJS from "exceljs";
import { beforeAll, describe, expect, it } from "vitest";

import { APP_NAME } from "@/lib/constants";
import { reportToCsv } from "@/lib/reports/csv";
import { reportFileName } from "@/lib/reports/filename";
import { isLinkableUrl, neutralizeFormula, reportRangeLabel } from "@/lib/reports/labels";
import { renderReportPdf } from "@/lib/reports/pdf";
import type { ReportData, ReportMeta } from "@/lib/reports/types";
import { reportToXlsx } from "@/lib/reports/xlsx";
import { utcToBusinessDate } from "@/lib/utils/dates";

import { buildEmptyDailyReport, buildSampleReport, FORMULA_START, parseCsv } from "../setup/report-fixtures";

// Report outputs (spec §19, §20): CSV/Excel with a formula-injection guard, a professional PDF, and safe
// download file names. Rendering runs under TZ=America/Los_Angeles, so times must still be IST.

const DAILY_HEADERS = [
  "Office",
  "Date",
  "Update Title",
  "Update Description",
  "Milestone Title",
  "Milestone Description",
  "Milestone Remarks",
  "Photos",
  "Documents",
];
const VISITOR_HEADERS = [
  "Office",
  "Date",
  "Name",
  "Purpose",
  "Arrival",
  "Departure",
  "Importance",
  "Remarks",
  "Photos",
  "Documents",
];
const CSV_COLUMNS = 10;

const pad = (cells: string[]) => [...cells, ...Array<string>(CSV_COLUMNS - cells.length).fill("")];

describe("formula-injection guard and labels", () => {
  it.each([
    ["=SUM(A1:A2)", "'=SUM(A1:A2)"],
    ["+1", "'+1"],
    ["-2+3", "'-2+3"],
    ["@SUM(A1)", "'@SUM(A1)"],
    ["\t=1", "'\t=1"],
    ["\r=1", "'\r=1"],
    [" =1+1", "' =1+1"],
    [" +cmd", "' +cmd"],
    ["Plain text", "Plain text"],
    ["a=b", "a=b"],
    ["", ""],
    ["'already quoted", "'already quoted"],
  ])("neutralizeFormula(%j) → %j", (input, expected) => {
    expect(neutralizeFormula(input)).toBe(expected);
  });

  it("formats range labels per report type", () => {
    expect(reportRangeLabel("daily", "2026-09-08", "2026-09-08")).toBe("08 Sep 2026");
    expect(reportRangeLabel("weekly", "2026-09-07", "2026-09-13")).toBe("07 Sep 2026 – 13 Sep 2026");
    expect(reportRangeLabel("monthly", "2026-09-01", "2026-09-30")).toBe("September 2026");
    expect(reportRangeLabel("custom", "2026-09-08", "2026-09-08")).toBe("08 Sep 2026");
  });

  it("only treats http(s) URLs as links", () => {
    expect(isLinkableUrl("https://res.cloudinary.com/x/raw/upload/a.pdf")).toBe(true);
    expect(isLinkableUrl("http://example.com")).toBe(true);
    for (const url of ["javascript:alert(1)", "data:text/html,<script>", "file:///etc/passwd", "mailto:a@b.c", "not a url"]) {
      expect(isLinkableUrl(url)).toBe(false);
    }
  });
});

describe("reportToCsv", () => {
  const data = buildSampleReport();
  const csv = reportToCsv(data);
  const rows = parseCsv(csv.slice(1));

  it("starts with a UTF-8 BOM and uses CRLF line endings throughout", () => {
    expect(csv.charCodeAt(0)).toBe(0xfeff);
    expect(csv.endsWith("\r\n")).toBe(true);
    expect(Buffer.from(csv, "utf8").subarray(0, 3).toString("hex")).toBe("efbbbf");
    // parseCsv throws on a bare LF/CR outside quoted fields.
    expect(rows.length).toBeGreaterThan(10);
  });

  it("pads every record to the same number of fields (RFC 4180 §2.4)", () => {
    for (const row of rows) expect(row).toHaveLength(CSV_COLUMNS);
  });

  it("writes the report header (spec §19)", () => {
    expect(rows.slice(0, 9)).toEqual([
      pad([APP_NAME]),
      pad(["Office", "All Offices"]),
      pad(["Report Type", "Weekly Report"]),
      pad(["Date Range", "07 Sep 2026 – 13 Sep 2026"]),
      pad(["Generated At", "15 Sep 2026, 10:05 AM"]),
      pad(["Generated By", "Komal Admin"]),
      pad([]),
      pad(["Daily Updates & Milestones"]),
      pad(DAILY_HEADERS),
    ]);
  });

  it("writes one row per milestone and one row for a record without milestones", () => {
    const dailyRows = rows.slice(9, rows.findIndex((row) => row[0] === "Visitors") - 1);
    expect(dailyRows).toHaveLength(2 + 4 + 1);
    expect(dailyRows[0]).toEqual([
      "Dean (Administration)",
      "2026-09-07",
      "Admissions review",
      'Reviewed, approved and "signed" the brochure.',
      "Brochure finalised",
      "Final proof approved by the Dean.",
      "Print order placed",
      "1 file: https://res.cloudinary.com/odums-demo/image/upload/v1757320000/office-daily-updates/DEAN-ADMIN/photos/meeting-room.jpg",
      "2 files: https://res.cloudinary.com/odums-demo/raw/upload/v1757320000/office-daily-updates/DEAN-ADMIN/documents/minutes-07-sep.pdf; javascript:alert(1)",
      "",
    ]);
    expect(dailyRows[6]?.slice(0, 7)).toEqual([
      "Dean (Administration)",
      "2026-09-10",
      "'-Negative start",
      "'\t=1+1 tab-prefixed formula",
      "",
      "",
      "",
    ]);
    expect(dailyRows[6]?.slice(7, 9)).toEqual(["0", "0"]);
  });

  it("quotes fields containing commas, quotes and new lines, doubling embedded quotes", () => {
    expect(csv).toContain('"\'+SUM(1,2) injection, ""quoted"" text, commas, and\nnew lines"');
    expect(csv).toContain('"Reviewed, approved and ""signed"" the brochure."');
    const injected = rows.find((row) => row[4] === "'=cmd|' /C calc'!A0");
    expect(injected?.[5]).toBe('\'+SUM(1,2) injection, "quoted" text, commas, and\nnew lines');
    expect(injected?.[6]).toBe("'@remark -starts with a formula character");
    // Multi-line descriptions keep their CRLFs inside the quoted field.
    expect(rows.some((row) => row[3]?.includes("\r\n\r\n"))).toBe(true);
    // Unicode is kept as-is.
    expect(rows.some((row) => row[2] === "Unicode: é ü “smart quotes” – dashes — ₹ 5,000 日本 😀 مرحبا")).toBe(true);
  });

  it("never emits a cell that a spreadsheet would evaluate as a formula", () => {
    for (const row of rows) {
      for (const cell of row) expect(cell, JSON.stringify(cell)).not.toMatch(FORMULA_START);
    }
  });

  it("writes visitors with IST times, blank departures and importance labels", () => {
    const start = rows.findIndex((row) => row[0] === "Visitors");
    expect(rows[start + 1]).toEqual(VISITOR_HEADERS);
    const visitorRows = rows.slice(start + 2);
    expect(visitorRows).toHaveLength(3 + 30);
    expect(visitorRows[0]).toEqual([
      "Dean (Administration)",
      "2026-09-07",
      "Dr. Anita Sharma",
      "Meeting regarding MoU renewal",
      "09:05 AM",
      "10:30 AM",
      "High",
      "Discussed collaboration, executive education.",
      "1 file: https://res.cloudinary.com/odums-demo/image/upload/v1757320000/office-daily-updates/DEAN-ADMIN/photos/visitor-badge.png",
      "0",
    ]);
    expect(visitorRows[1]?.slice(2, 8)).toEqual([
      "'=HYPERLINK(\"http://evil.example\",\"click\")",
      "'-2+3",
      "02:15 PM",
      "",
      "Low",
      "' =1+1 leading space",
    ]);
    // 23:45 IST stays on its business date and is not shifted by the server timezone.
    expect(visitorRows[2]?.slice(1, 6)).toEqual(["2026-09-08", "Mr. Rajesh Kumar Venkataraman", expect.any(String), "11:45 PM", "11:59 PM"]);
    expect(visitorRows.slice(3).every((row) => row[0] === "Human Resources")).toBe(true);
  });

  it("writes empty-state messages (spec §40)", () => {
    const single = parseCsv(reportToCsv(buildEmptyDailyReport()).slice(1));
    expect(single[3]).toEqual(pad(["Date", "12 Sep 2026"]));
    expect(single).toContainEqual(pad(["No daily update has been recorded for this date."]));
    expect(single).toContainEqual(pad(["No visitors found."]));

    const range = buildEmptyDailyReport();
    range.meta = { ...range.meta, type: "custom", typeLabel: "Custom Report", to: "2026-09-14", rangeLabel: "12 Sep 2026 – 14 Sep 2026" };
    const rangeRows = parseCsv(reportToCsv(range).slice(1));
    expect(rangeRows[3]).toEqual(pad(["Date Range", "12 Sep 2026 – 14 Sep 2026"]));
    expect(rangeRows).toContainEqual(pad(["No daily updates have been recorded for this period."]));
  });

  it("guards header values supplied by users (office names, generatedBy)", () => {
    const data = buildEmptyDailyReport();
    data.meta = { ...data.meta, officeLabel: "=Evil Office", generatedBy: "@attacker" };
    const headerRows = parseCsv(reportToCsv(data).slice(1));
    expect(headerRows[1]?.[1]).toBe("'=Evil Office");
    expect(headerRows[5]?.[1]).toBe("'@attacker");
  });
});

type LoadedCell = ExcelJS.Cell;

function cellText(cell: LoadedCell): string | null {
  const value = cell.value;
  if (typeof value === "string") return value;
  if (value && typeof value === "object" && "text" in value && typeof value.text === "string") return value.text;
  if (value && typeof value === "object" && "richText" in value) return value.richText.map((part) => part.text).join("");
  return null;
}

function rowTexts(sheet: ExcelJS.Worksheet, rowNumber: number): (string | number | null)[] {
  const row = sheet.getRow(rowNumber);
  const values: (string | number | null)[] = [];
  for (let column = 1; column <= row.cellCount; column += 1) {
    const cell = row.getCell(column);
    values.push(typeof cell.value === "number" ? cell.value : cellText(cell));
  }
  return values;
}

async function loadWorkbook(data: ReportData): Promise<ExcelJS.Workbook> {
  const buffer = await reportToXlsx(data);
  expect(Buffer.isBuffer(buffer)).toBe(true);
  expect(buffer.subarray(0, 2).toString("latin1")).toBe("PK");
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer as unknown as ExcelJS.Buffer);
  return workbook;
}

function sheet(workbook: ExcelJS.Workbook, name: string): ExcelJS.Worksheet {
  const found = workbook.getWorksheet(name);
  if (!found) throw new Error(`Missing worksheet "${name}"`);
  return found;
}

describe("reportToXlsx", () => {
  let workbook: ExcelJS.Workbook;

  beforeAll(async () => {
    workbook = await loadWorkbook(buildSampleReport());
  });

  it("creates the Summary, Daily Updates, Milestones, Visitors and Attachments sheets", () => {
    expect(workbook.worksheets.map((worksheet) => worksheet.name)).toEqual([
      "Summary",
      "Daily Updates",
      "Milestones",
      "Visitors",
      "Attachments",
    ]);
    expect(workbook.creator).toBe(APP_NAME);
  });

  it("writes the summary header and per-office totals with an overall total", () => {
    const summary = sheet(workbook, "Summary");
    expect(cellText(summary.getCell("A1"))).toBe(APP_NAME);
    expect(rowTexts(summary, 3)).toEqual(["Office", "All Offices"]);
    expect(rowTexts(summary, 4)).toEqual(["Report Type", "Weekly Report"]);
    expect(rowTexts(summary, 5)).toEqual(["Date Range", "07 Sep 2026 – 13 Sep 2026"]);
    expect(rowTexts(summary, 6)).toEqual(["Generated At", "15 Sep 2026, 10:05 AM"]);
    expect(rowTexts(summary, 7)).toEqual(["Generated By", "Komal Admin"]);
    expect(rowTexts(summary, 9)).toEqual(["Office", "Code", "Daily Updates", "Milestones", "Visitors", "Photos", "Documents"]);
    expect(rowTexts(summary, 10)).toEqual(["Dean (Administration)", "DEAN-ADMIN", 3, 6, 3, 5, 3]);
    expect(rowTexts(summary, 11)).toEqual(["Human Resources", "HR", 0, 0, 30, 0, 0]);
    expect(rowTexts(summary, 12)).toEqual(["XLRI Leadership & Excellence Academy", "XLEAD", 0, 0, 0, 0, 0]);
    const total = rowTexts(summary, 13);
    expect(total[0]).toBe("Total");
    expect(total.slice(2)).toEqual([3, 6, 33, 5, 3]);
  });

  it("writes bold, frozen header rows on every data sheet", () => {
    const headers: Record<string, string[]> = {
      "Daily Updates": ["Office", "Date", "Update Title", "Update Description", "Milestones", "Photos", "Documents"],
      Milestones: ["Office", "Date", "Update Title", "No.", "Milestone Title", "Milestone Description", "Remarks"],
      Visitors: VISITOR_HEADERS,
      Attachments: ["Office", "Date", "Record", "Record Title", "Type", "File Name", "File URL"],
    };
    for (const [name, expected] of Object.entries(headers)) {
      const worksheet = sheet(workbook, name);
      expect(rowTexts(worksheet, 1), name).toEqual(expected);
      expect(worksheet.getRow(1).getCell(1).font?.bold, name).toBe(true);
      expect(worksheet.views[0], name).toMatchObject({ state: "frozen", ySplit: 1 });
    }
  });

  it("writes one daily row per record and one milestone row per milestone", () => {
    const daily = sheet(workbook, "Daily Updates");
    expect(daily.actualRowCount).toBe(1 + 3);
    expect(rowTexts(daily, 2)).toEqual([
      "Dean (Administration)",
      null,
      "Admissions review",
      'Reviewed, approved and "signed" the brochure.',
      2,
      "meeting-room.jpg",
      "minutes-07-sep.pdf\n'=bad-link.pdf",
    ]);

    const milestones = sheet(workbook, "Milestones");
    expect(milestones.actualRowCount).toBe(1 + 6);
    expect(rowTexts(milestones, 3)).toEqual([
      "Dean (Administration)",
      null,
      "Admissions review",
      2,
      "'=cmd|' /C calc'!A0",
      '\'+SUM(1,2) injection, "quoted" text, commas, and\nnew lines',
      "'@remark -starts with a formula character",
    ]);
  });

  it("stores business dates as real Excel dates that keep their calendar day", () => {
    const expectations: [string, number, string][] = [
      ["Daily Updates", 2, "2026-09-07"],
      ["Daily Updates", 4, "2026-09-10"],
      ["Milestones", 4, "2026-09-08"],
      ["Visitors", 4, "2026-09-08"],
      ["Attachments", 2, "2026-09-07"],
    ];
    for (const [name, rowNumber, expected] of expectations) {
      const cell = sheet(workbook, name).getRow(rowNumber).getCell(2);
      expect(cell.value, `${name} row ${rowNumber}`).toBeInstanceOf(Date);
      expect(utcToBusinessDate(cell.value as Date)).toBe(expected);
      expect(cell.numFmt).toBe("dd mmm yyyy");
    }
  });

  it("writes visitors with IST times and guarded text", () => {
    const visitors = sheet(workbook, "Visitors");
    expect(visitors.actualRowCount).toBe(1 + 33);
    expect(rowTexts(visitors, 2).slice(2, 8)).toEqual([
      "Dr. Anita Sharma",
      "Meeting regarding MoU renewal",
      "09:05 AM",
      "10:30 AM",
      "High",
      "Discussed collaboration, executive education.",
    ]);
    expect(rowTexts(visitors, 3).slice(2, 8)).toEqual([
      "'=HYPERLINK(\"http://evil.example\",\"click\")",
      "'-2+3",
      "02:15 PM",
      "",
      "Low",
      "' =1+1 leading space",
    ]);
  });

  it("lists attachments with clickable links only for http(s) URLs", () => {
    const attachments = sheet(workbook, "Attachments");
    expect(attachments.actualRowCount).toBe(1 + 8);

    const photo = attachments.getRow(2);
    expect(rowTexts(attachments, 2).slice(2, 5)).toEqual(["Daily Update", "Admissions review", "Photo"]);
    expect(photo.getCell(6).value).toEqual({
      text: "meeting-room.jpg",
      hyperlink:
        "https://res.cloudinary.com/odums-demo/image/upload/v1757320000/office-daily-updates/DEAN-ADMIN/photos/meeting-room.jpg",
    });

    const unsafe = attachments.getRow(4);
    expect(cellText(unsafe.getCell(6))).toBe("'=bad-link.pdf");
    expect(unsafe.getCell(6).hyperlink).toBeUndefined();
    expect(cellText(unsafe.getCell(7))).toBe("javascript:alert(1)");

    const visitorFiles = [8, 9].map((rowNumber) => rowTexts(attachments, rowNumber).slice(2, 6));
    expect(visitorFiles).toEqual([
      ["Visitor", "Dr. Anita Sharma", "Photo", "visitor-badge.png"],
      ["Visitor", "Mr. Rajesh Kumar Venkataraman", "Document", "proposal-wifi.docx"],
    ]);
  });

  it("contains no formulas and no text cell starting with a formula character", () => {
    let checked = 0;
    for (const worksheet of workbook.worksheets) {
      worksheet.eachRow({ includeEmpty: false }, (row) => {
        row.eachCell({ includeEmpty: false }, (cell) => {
          expect(cell.type, `${worksheet.name}!${cell.address}`).not.toBe(ExcelJS.ValueType.Formula);
          const text = cellText(cell);
          if (text !== null) {
            checked += 1;
            expect(text, `${worksheet.name}!${cell.address}`).not.toMatch(FORMULA_START);
          }
        });
      });
    }
    expect(checked).toBeGreaterThan(200);
  });

  it("writes empty-state rows and no total row for a single-office report", async () => {
    const empty = await loadWorkbook(buildEmptyDailyReport());
    expect(rowTexts(sheet(empty, "Summary"), 5)).toEqual(["Date", "12 Sep 2026"]);
    expect(rowTexts(sheet(empty, "Summary"), 10)).toEqual(["Registrar", "REG", 0, 0, 0, 0, 0]);
    expect(sheet(empty, "Summary").actualRowCount).toBe(8);
    expect(cellText(sheet(empty, "Daily Updates").getCell("A2"))).toBe("No daily update has been recorded for this date.");
    expect(cellText(sheet(empty, "Milestones").getCell("A2"))).toBe("No milestones have been added yet.");
    expect(cellText(sheet(empty, "Visitors").getCell("A2"))).toBe("No visitors found.");
    expect(cellText(sheet(empty, "Attachments").getCell("A2"))).toBe("No attachments.");
  });
});

function pdfPageCount(pdf: Buffer): number {
  return (pdf.toString("latin1").match(/\/Type\s*\/Page(?![a-zA-Z])/g) ?? []).length;
}

describe("renderReportPdf", () => {
  it("renders a multi-page A4 PDF for a realistic all-offices report", async () => {
    const data = buildSampleReport();
    const snapshot = JSON.stringify(data);
    const pdf = await renderReportPdf(data);

    expect(Buffer.isBuffer(pdf)).toBe(true);
    expect(pdf.subarray(0, 5).toString("latin1")).toBe("%PDF-");
    expect(pdf.subarray(-7).toString("latin1")).toContain("%%EOF");
    expect(pdf.length).toBeGreaterThan(10_000);
    expect(pdfPageCount(pdf)).toBeGreaterThanOrEqual(2);
    expect(pdf.toString("latin1")).toMatch(/\/MediaBox\s*\[\s*0 0 595\.2?8?\d* 841\.8\d*\s*\]/);
    // Rendering does not mutate the report.
    expect(JSON.stringify(data)).toBe(snapshot);

    // Attachment links are real URI annotations for http(s) files only (spec §19 "links where appropriate").
    const raw = pdf.toString("latin1");
    expect(raw).toMatch(/\/URI\s*\(https:\/\/res\.cloudinary\.com\/odums-demo\/raw\/upload\/[^)]*minutes-07-sep\.pdf\)/);
    expect(raw).not.toContain("javascript:");
  }, 60_000);

  it("renders a single-page PDF for an empty single-office daily report", async () => {
    const pdf = await renderReportPdf(buildEmptyDailyReport());
    expect(pdf.subarray(0, 5).toString("latin1")).toBe("%PDF-");
    expect(pdf.length).toBeGreaterThan(1_500);
    expect(pdfPageCount(pdf)).toBe(1);
  }, 60_000);
});

describe("reportFileName", () => {
  const base: ReportMeta = buildSampleReport().meta;
  const meta = (overrides: Partial<ReportMeta>): ReportMeta => ({ ...base, ...overrides });

  it.each([
    ["all offices, weekly range", meta({}), "pdf", "report-weekly-all-offices-2026-09-07-to-2026-09-13.pdf"],
    [
      "single office daily",
      meta({ type: "daily", officeId: "64f1", officeLabel: "Dean (Admin) & HR", from: "2026-09-08", to: "2026-09-08" }),
      "csv",
      "report-daily-dean-admin-hr-2026-09-08.csv",
    ],
    [
      "monthly uses the month only",
      meta({ type: "monthly", officeId: "64f1", officeLabel: "Office A", from: "2026-09-01", to: "2026-09-30" }),
      "xlsx",
      "report-monthly-office-a-2026-09.xlsx",
    ],
    [
      "custom single day",
      meta({ type: "custom", officeId: null, from: "2026-09-08", to: "2026-09-08" }),
      "pdf",
      "report-custom-all-offices-2026-09-08.pdf",
    ],
    [
      "accents are transliterated, quotes and paths dropped",
      meta({ officeId: "64f1", officeLabel: 'Café "Ünïcode" / ../../etc 日本' }),
      "csv",
      "report-weekly-cafe-unicode-etc-2026-09-07-to-2026-09-13.csv",
    ],
    ["non-Latin office names fall back to office", meta({ officeId: "64f1", officeLabel: "प्रशासन 日本" }), "pdf", "report-weekly-office-2026-09-07-to-2026-09-13.pdf"],
    ["extension is normalised", meta({}), ".PDF", "report-weekly-all-offices-2026-09-07-to-2026-09-13.pdf"],
    ["unsafe extension characters are removed", meta({}), 'x"/../y', "report-weekly-all-offices-2026-09-07-to-2026-09-13.xy"],
    ["empty extension becomes bin", meta({}), "", "report-weekly-all-offices-2026-09-07-to-2026-09-13.bin"],
  ])("%s", (_label, input, extension, expected) => {
    expect(reportFileName(input, extension)).toBe(expected);
  });

  it("caps long office slugs at 60 characters without a trailing hyphen", () => {
    const name = reportFileName(
      meta({ type: "daily", officeId: "64f1", officeLabel: `${"Department of ".repeat(10)}Studies`, from: "2026-09-08", to: "2026-09-08" }),
      "pdf",
    );
    const slug = name.replace(/^report-daily-/, "").replace(/-2026-09-08\.pdf$/, "");
    expect(slug.length).toBeLessThanOrEqual(60);
    expect(slug).not.toMatch(/-$/);
    expect(slug.startsWith("department-of-department-of")).toBe(true);
  });

  it("always produces a header-safe ASCII name", () => {
    const hostile = ['a"; filename=evil.exe', "..\\..\\x", "\r\nSet-Cookie: x=1", "😀", "Office‮gpj.exe"];
    for (const officeLabel of hostile) {
      const name = reportFileName(meta({ officeId: "64f1", officeLabel }), "pdf");
      expect(name).toMatch(/^report-weekly-[a-z0-9-]+-2026-09-07-to-2026-09-13\.pdf$/);
    }
  });
});
